### ISSUE TITLE
A list of all currency

### ISSUE THREAD

**Issue by AmirAliRashidi** [margani/pricedb#2]
سلام و عرض ادب
سوال اول اینکه دیتا ها ریل تایم هستند یا خیر؟
و سوال دوم آیا امکانش هست لیست کامل قیمت ها را گرفت؟
برای مثال با یک api هم قیمت دلار، پوند، یورو و ... را برگرداند

**Comment by margani** [comment]
سلام.

ممنونم.

قیمت ها ریل تایم نیست خیر. روزی یه بار در انتهای روز قیمت ها از سایت tgju.org گرفته میشه و توی همین ریپازیتوری ثبت میشه. و به انتهای تاریخچه اون آیتم هم افزوده میشه. کلا نمیتونه ریل تایم باشه. اما میشه نزدیکتر به ریل تایم بشه. ولی در حال حاضر امکانش نیست.

برای گرفتن قیمت چند آیتم باید برای هر آیتم باید یه درخواست جداگانه به latest.json بدید. امکانش نیست چند قیمت توی یه پاسخ باشه.

**Comment by margani** [comment]
#4

**Comment by AmirAliRashidi** [comment]
تشکر از توضیحاتتون
من یه سایت دیده بودم که عکس با آیکون ریسپانسش بود https://skillicons.dev/icons که توی پارامز اسم آیکن ها با کاما ارسال میشد و برمیگردوند
گفتم اگر امکانش باشه اسامی ارز ها توی پارامز ارسال بشه و برگردونه جالب میشه اما چون میگید از ریپازیتوری گیتهاب میخونه فعلا امکانش نیست فکر کنم
بازم ممنون🙏🏻
