### ISSUE TITLE
IRR USD Shows 0 

### ISSUE THREAD

**Issue by ghost** [margani/pricedb#22]
قیمت دلار در تمام قسمت ها 0 نمایش داده میشه, این مشکل از امروز صبح اتفاق افتاده

![Screenshot from 2024-05-28 18-18-05](https://github.com/margani/pricedb/assets/80700894/780ba7a9-0a6a-4676-82c2-85c948ffc543)

**Comment by margani** [comment]
قیمت دلار در خود سایت tgju.org به ندرت بروزرسانی میشه که دلایل زیادی میتونه داشته باشه:
* وقتی قیمت دلار جهش زیادی دارهُ معمولا این سایت دیگه قیمت رو نشون نمیده، ولی گاهی در خروجی API نشون میده.
* امروز جمعه است و بعید نیست دلیل صفر بودن قیمت همین باشه.

اما اینجا یه باگ هست توی کد که latest قیمت آخر رو نمیده، بلکه قیمت آخر که از اون سایت گرفته رو میده. این رو بزودی تصحیح میکنم.

**Comment by ghost** [comment]
ممنون بابت آپدیت
