### ISSUE TITLE
هنگام curl زدن اطلاعات بصورت JSON برنمیگرده.

### ISSUE THREAD

**Issue by ghost** [margani/pricedb#24]
**Describe the bug**
هنگام curl زدن اطلاعات بصورت JSON برنمیگرده.

**To Reproduce**
```
curl --request GET \
     --url https://api.priceto.day/v1/latest/irr/usd \
     --header 'accept: application/json'
```

**Screenshots**
![Screenshot from 2024-08-08 16-17-59](https://github.com/user-attachments/assets/b1e17ab4-b253-46de-9a48-082938e51539)

**Additional context**
بنظر داخل مرورگر همه چیز اوکیه اما داخل کد پاسخ HTML میاد. 
تصویر داخل مرورگر:
![Screenshot from 2024-08-08 16-20-15](https://github.com/user-attachments/assets/1201a2f7-4672-4a3f-a0f4-6b90860866a2)

**Comment by margani** [comment]
This API is hosted on a free version of Netlify, which has a limit on the number of executions.

To avoid exceeding this limit, I have setup a Rate Limit policy to block the sources that are sending many requests.

The first picture is the result of such requests.

The API endpoint you are hitting (`https://api.priceto.day/v1/latest/irr/usd` ) does not provide such a real time data. It means you don't need to request this URL more than once in at most 15 minutes. The source of the data rarely updates the data in less than an hour.

So you have two options:

1. Send less requests to the API, for example at most once every 15 minutes.
2. Use the other API endpoint which is direct JSON file in GitHub. This doesn't have any limit. So in your application replace `https://api.priceto.day/v1/latest/irr/usd` with `https://raw.github.com/margani/pricedb/main/tgju/current/price_dollar_rl/latest.json`. 

   The `api.priceto.day` API is exactly doing this [here](https://github.com/margani/pricedb/blob/e7a024f5cd29fc18ee5764ca73479740dbebc888/netlify/functions/v1-latest/index.mjs#L9-L18). 
   As you can see for getting USD which is a well-known currency, we map it to the `price_dollar_rl` which is the currency name in the source website. If you want a currency other than USD, you can find its mapping [here](https://github.com/margani/pricedb/blob/e7a024f5cd29fc18ee5764ca73479740dbebc888/src/utils/constants.js#L6-L14).
